services:
  app:
    container_name: app
    build: .
    tty:
      true
    volumes:
      - ./:/app:cached
      - type: volume
        source: node-modules
        target: /app/node_modules

volumes:
  node-modules: